#!/usr/bin/env python3
"""
Asynchronously collects 10 random floats generated by async_generator.
Returns a list of these floats."""

import asyncio
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronously collects 10 random floats generated by async_generator.
    Returns a list of these floats.
    """
    return [i async for i in async_generator()]
